// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"websocket_demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:hub/ws",
				Handler: wsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: listHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/close/:hub",
				Handler: closeHandler(serverCtx),
			},
		},
	)
}
